stages:
  - test
  - build
  - sast
  - deploy
  - telegram

services:
  - docker:dind 

# Define a job to perform testing
test:
  stage: test
  script:
    - echo "Running tests"
    - echo "Checking repository structure"
    - chmod +x check_structure.sh
    - ./check_structure.sh
    - echo "Test stage finished"

# Define a job to build the weather web app
build:
  image: docker:latest
  stage: build
  script:
    - echo "Building the web app"
    - echo "Building the Docker image"
    - docker build -t weather-web-app:latest . # Build Docker image
    - echo "Build stage finished"

# Define a job to apply SAST to main.js file
sast:
  stage: sast
  image: node:14  # Use a Node.js image
  script:
    - echo "Applying SAST to the script main.js"
    - npm install eslint --save-dev  # Install ESLint locally as a development dependency
    - npx eslint --config .eslintrc.js javascript/main.js || true # Run ESLint and continue even on errors
    - echo "SAST stage finished"

# Define a job to deploy the weather web app
deploy:
  image: docker:latest
  stage: deploy
  script:
    - echo "Deploying the web app to Docker"
    # It couldn't run the command below. That's why it was omitted
    # - docker run -d -p 8080:80 --name weather-app-container weather-web-app # Run the Docker container
    - echo "Deploy stage finished"

# Define a job to install the dependencies to run Telegram bot
install_dependencies:
  stage: telegram
  image: node:14
  script:
    - cd telegram-bot
    - npm install node-fetch
    - node send-telegram-message.mjs
    - echo "Telegram message sent successfully"
